roles/nginx/tasks/install-Debian.yml
Because of the following `DEPRECATION WARNING`:
```
TASK [nginx : Ensure nginx server is installed (Debian)] *****************************************************************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via squash_actions is deprecated. Instead of using a loop to supply multiple 
items and specifying `name: "{{ item }}"`, please use `name: ['nginx']` and remove the loop. This feature will be removed in version 2.11. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
=> DEVOPS-106 Migration tests of the (RCIAM) role NGINX in Ansible 2.9.

roles/shibboleth-sp/templates/shibboleth2.xml.j2
Fix typo error. forchAuthn config in SSO must be renamed to forceAuthn
=> Bug fix shibboleth2.xml.j2

roles/ssp/tasks/configure-common.yml
```bash
ERROR! The requested handler 'restart apache' was not found in either the main handlers list nor in the listening handlers list
```
=> notify: restart webserver

roles/ssp/templates/config/config-1.17.php.j2
It all started from this tasks [devel/roles/ssp/tasks/configure-common.yml](https://github.com/rciam/rciam-deploy/blob/devel/roles/ssp/tasks/configure-common.yml#L44-L52), with this template [devel/roles/ssp/templates/config/config-1.17.php.j2](https://github.com/rciam/rciam-deploy/blob/devel/roles/ssp/templates/config/config-1.17.php.j2#L664-L677) :
```
{% if ssp_memcache_store_servers is defined %}
'memcache_store.servers' => [
{% for group in ssp_memcache_store_servers %}
[
{% for host in group %}
[
'hostname' => '{{ host }}',
'timeout' => 1,
],
{% endfor %}
],
{% endfor %}
],
{% endif %}
```
If in `rciam-deploy-inv/eosc-portal-demo/hosts.ini` there was _only one entry_ below the group `cache` then I get the following error:
<details>
<summary> Ansible FAILED </summary>
```bash
TASK …
```
=> Dynamic find of "memcache_store.servers".

roles/ssp/templates/config/config-1.17.php.j2
Follow the dynamic way only when the variable `ssp_memcache_store_servers` does not exist.
=> Fix dynamic way for SSP memcache servers.

roles/tomcat/defaults/main.yml, roles/tomcat/templates/server.xml.j2
Add configuration options to setup tomcat in cluster mode using StaticMembershipInterceptor class.
More info about the configuration can be found in RCIAM-271 ticket.
=> Support tomcat static cluster configuration

roles/ssp/defaults/main.yml, roles/ssp/handlers/main.yml, roles/ssp/tasks/configure-common.yml, roles/ssp/tasks/install-common.yml, roles/ssp/tasks/main.yml
If `ssp_version_suffix` is defined, the ssp directory name will have a specific **suffix**.
In addition, a symbolic link in `/srv/simplesamlphp/proxy-current` to `/srv/simplesamlphp/proxy-example-dir/www/` will now be created.
This way we will have a fixed link file `/srv/simplesamlphp/proxy-current` which will redirect to the version of the SSP we want each time.
The web server now only needs to have this DocumentRoot : `/srv/simplesamlphp/proxy-current`.
* :link: https://github.com/grnet/rciam-deploy-inv/pull/32
* :link: https://github.com/grnet/rciam-deploy-inv/pull/34
=> Multiple versions of SimpleSAMLphp.

roles/ssp/defaults/main.yml, roles/ssp/templates/config/authsources-1.14.php.j2, roles/ssp/templates/config/authsources-1.17.php.j2, roles/ssp/templates/config/authsources-1.18.php.j2
Extend SSP authsources.php.j2 template in order to support raw php
=> Extend_ssp_authsources_template

roles/fedreg-agent/templates/deployer_mitreid.service.j2, roles/fedreg-agent/templates/deployer_ssp.service.j2
Add restart interval in the service files as this caused problem when the deployers were exiting with an error.
The problem was that the service tried to restart too soon and caused the service to crash
=> Add restart interval

roles/comanage-registry-plugins/defaults/main.yml, roles/comanage-registry-plugins/tasks/configure.yml, roles/comanage-registry/defaults/main.yml, roles/comanage-registry/tasks/configure.yml
Cron jobs deploy only in one node
=> Cronjobs_run_once_comanage_registry_role

roles/keycloak/tasks/blocks/configure_federations.yml, roles/keycloak/tasks/blocks/configure_saml_idps.yml, roles/keycloak/tasks/blocks/configure_social_idps.yml, roles/keycloak/tasks/blocks/helpers/get_realm_federations.yml
Changed the role to allow updating all  idps and federations, on subsequest calls with a different config
=> IdP and federation role config now allows updates on subsequent executions

roles/keycloak/tasks/blocks/configure_federations.yml
Skip configuring the federation's mappers if none (federation mappers) are defined.
=> [keycloak role] - minor loop bordercase fix

roles/keycloak/tasks/blocks/configure_client_scopes.yml, roles/keycloak/tasks/blocks/helpers/unassign_default_client_scopes.yml, roles/keycloak/tasks/blocks/helpers/unassign_default_default_client_scope.yml, roles/keycloak/tasks/blocks/helpers/unassign_default_optional_client_scope.yml, roles/keycloak/tasks/configure.yml
This PR is an update of [RCIAM-793](https://jira.argo.grnet.gr/browse/RCIAM-793) to be able to assign client scopes into default and optional categories, in order to be able to apply the requirements of [RCIAM-814](https://jira.argo.grnet.gr/browse/RCIAM-814)
=> Rciam 793 and 814

roles/keycloak/defaults/main.yml, roles/keycloak/tasks/blocks/configure_basic_realm.yml, roles/keycloak/tasks/blocks/roles_configuration/configure.yml, roles/keycloak/tasks/blocks/roles_configuration/configure_default_roles.yml, roles/keycloak/tasks/blocks/roles_configuration/configure_role_composites.yml, roles/keycloak/tasks/blocks/roles_configuration/configure_roles.yml, roles/keycloak/tasks/configure.yml
By integrating this change, whenever we want to alter a new property of the realm we will just need 
- to alter/add only the equivalent parameter on the `rciam-deploy-inv` 
- rather than editing the placeholders in this role and then also adding the values in the `rciam-deploy-inv`
It also merges the basic realm config parameters into a single call.
Also, this PR enables managing realm's roles:
- can create/update realm roles
- can set default realm roles
- can configure composite roles for the realm
=> [keycloak role] Changes the realm creation/update to be more generic and enables realm roles management   

roles/keycloak/tasks/configure.yml, roles/keycloak/tasks/main.yml
Fixes a mistake in the logic... 
The logs folder creation (and moving) should be done JUST before anything related to the keycloak installation begins. 
Also, the keycloak must ALWAYS be restarted if there is any change in the filesystem or the keycloak configuration.
=> [keycloak role] Fixed a stupid mistake in the log cleanup flow

roles/keycloak/defaults/main.yml
related ticket: [RCIAM-894](https://jira.argo.grnet.gr/browse/RCIAM-894)
This just adds the variable in the sample (just for documentation purposes)
=> [keycloak role] Added in the defaults a sample value for hide.from.openID.provider.metadata

roles/keycloak/templates/15.0.2/standalone-ha.xml.j2, roles/keycloak/templates/16.1.0/standalone-ha.xml.j2
This PR is for increasing the jboss transaction timeout (bumped to 600 from the default 300) to allow updating the federation IdPs without timing out halfway.
=> [keycloak role] standalone-ha.xml.j2 change default transaction timeout

roles/keycloak/defaults/main.yml, roles/keycloak/templates/16.1.0/standalone-ha.xml.j2
According to [this](https://jira.argo.grnet.gr/browse/RCIAM-922) ticket
=> keycloak role: added a keycloak-logs-level for SAML protocol (default: INFO)

roles/keycloak/tasks/java/Debian-10.yml
In case that the apt runs first time on the machine, it needs to update, because it might have a outdated list of packages.
This is idempotent.
=> [keycloak role] 

roles/keycloak/tasks/configure.yml
I believe that i've found the offending task which leads to the http-401 in various cases. 
I managed to replicate the faulty scenario on the `kc-stable` deployment. 
By removing this task, it seems that the (synchronization?) issues which lead to the failure dissapear. 
Moreover, the next blocks have their own token renewal, so they are not affected by this removal.
I made a couple of tests after the removal, and i didn't get any failures.
=> [keycloak role] removed an extra access token request

roles/rciam-metrics/tasks/main.yml
"include" has been deprecated in v2.4 and removed in v2.16
=> Replace "include" tasks deprecated in Ansible v2.4

roles/keycloak/tasks/blocks/authentication/configure_first_broker_login.yml
From Keycloak version _22.0.10-1.4rc2_ _terms_and_conditions_ has been added to _review profile config_ execution flow.
With the following addition, we check if at least one config for _review profile config_ execution flow exists.
Default value are default Keycloak values.
In previous Keycloak version, _terms_and_conditions_ does not exist.
I propose to add the PR and run to all Keycloak version.
In previous from _22.0.10-1.4rc2_  versions, an unnecessary value will be added. No problem.
Otherwise, for newer from _22.0.10-1.4rc2_  versions - and without this addition - _terms_and_conditions_ will be removed. It will take the default value (false).
=> Proposed configuration for changing terms_and_conditions

.gitignore, roles/keycloak/defaults/main.yml, roles/keycloak/tasks/blocks/authentication/configure_first_broker_login.yml
Although I believe that we should put first-broker-login flow as we do with browser flow, this will mean changes in all rciam-deploy-inv
=> Add Missing only to default - add hideUsername configuration
