rciam/rciam-deploy

roles/postgresql/defaults/main.yml
roles/postgresql/tasks/configure-common.yml
roles/postgresql/templates/pg_hba.conf.j2
roles/postgresql/templates/postgresql.conf.j2

changed pg_hba.con.j2 and the vars yaml file so as to support dynamically multiple hosts

rciam roles update

---

roles/shibboleth-sp/files/attribute-map.xml

Add voPersonVerifiedEmail attribute

ADD_voPersonVerifiedEmail_attribute-map.xml

---

roles/tomcat/defaults/main.yml
roles/tomcat/templates/server.xml.j2

This PR contains the following changes:
- Modify the type of `tomcat_cluster` array to object
- Fix the intents of server.xml.j2 template

Update tomcat role

---

config/PLACEHOLDER/secrets_env.yml.PLACEHOLDER
secrets.yml

The `ssp` role needs some variables to run for the first time.
In order to help the user to create these variables, we decided to generate these values through an Ansible Playbook.
After the execution of the `secrets.yml` Ansible Playbook, all you have to do is go to the `config/PLACEHOLDER/` directory and copy the values you want or if you want, you [can also define the location and name](https://github.com/Tas-sos/rciam-deploy/blob/secrets/secrets.yml#L8-L10) of the generated file in order to use it directly like a host_var or group_var.
This playbook create a sample file with the following generated variables : 
```
ansible-playbook -u debian --vault-password-file=../vaultRCIAM secrets.yml -i rciam-deploy-inv/eosc-portal-demo/hosts.ini
```
<details>
<summary> 1st execution </summary> …

Add secrets.yml Playbook

---

roles/rciam-probes/tasks/configure-RedHat.yml

Enable search permissions for nagios home directory

FIX_rciam_probe_search_permissions

---

roles/ssp/handlers/main.yml
roles/ssp/tasks/configure-common.yml
roles/ssp/tasks/install-common.yml

Always update symbolic link.

---

roles/ssp/defaults/main.yml
roles/ssp/tasks/install-common.yml
roles/ssp/templates/config/config-1.18.php.j2

Twig templates.
=============
The new **Twig** templates require **npm** and a few extra steps during installation.
Node.js v**14.15.1** is installed via **nvm**, in order to avoid future problems with _different_ versions of Node.js.
Examples
=========
```bash
ansible-playbook -u debian -i rciam-deploy-inv/eosc-portal-demo/hosts.ini saml2samlservers.yml --vault-password-file=../vaultRCIAM --tags "ssp:install, ssp:config:config"
```
<details>
<summary>ssp_twig_template: false ( default ) </summary>
```
TASK [ssp : Define SSP path] ****************************************************************
task path: /rciam-deploy/roles/ssp/tasks/main.yml:41
ok: [testVM] => changed=false 
ansible_facts:
ssp_path: /srv/simplesamlphp/proxy-rciam-1.18
TASK [ssp : Update package cache (Debian)] …
```

DEVOPS-351 Improving the installation steps.

---

roles/ssp-modules/defaults/main.yml
roles/ssp-modules/tasks/configure-common.yml
roles/ssp-modules/tasks/install-common.yml
roles/ssp-modules/tasks/main.yml

Example
========
```
ansible-playbook -u debian -i rciam-deploy-inv/eosc-portal-demo/hosts.ini saml2samlservers.yml --vault-password-file=../vaultRCIAM --tags "ssp_modules:dict"
```
```
TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [example.com]
TASK [ssp-modules : Include OS-specific variables] ****************************************************************************************************************************************************************
ok: [example.com] => (item=/..../rciam-deploy/roles/ssp-modules/vars/Debian.yml)
TASK [ssp-modules : Add extra dictionaries] …
```

Add extra dictionaries.

---

roles/ssp-module-proxystatistics/defaults/main.yml
roles/ssp-module-proxystatistics/templates/config/module_statisticsproxy-rciam-2.5.php.j2
roles/ssp-module-proxystatistics/templates/config/module_statisticsproxy-rciam-3.0.php.j2

Identifier Blacklist - Proxystatistics Role

Proxystatistics_ident_blacklist

---

registryservers.yml
roles/comanage-registry/defaults/main.yml
roles/comanage-registry/tasks/configure.yml
roles/comanage-registry/tasks/initialize.yml
roles/comanage-registry/tasks/install.yml
roles/comanage-registry/tasks/main.yml
roles/comanage-registry/tasks/static_files.yml
roles/comanage-registry/templates/core.php.j2
roles/comanage-registry/templates/security.salt.j2
roles/comanage-registry/templates/security.seed.j2

COmanage_role_refactor

---

registryservers.yml
roles/comanage-registry-plugins/defaults/main.yml
roles/comanage-registry-plugins/tasks/configure.yml
roles/comanage-registry-plugins/tasks/install.yml
roles/comanage-registry-plugins/tasks/main.yml
roles/comanage-registry-plugins/tasks/preinstall.yml
roles/comanage-registry-plugins/vars/Debian.yml

Ansible Role for COmanage Registry Plugins

COmanage_plugins_role

---

roles/comanage-registry-plugins/defaults/main.yml
roles/comanage-registry-plugins/tasks/configure.yml

CMG_plugins-configure-symlinks

---

roles/comanage-registry/defaults/main.yml
roles/comanage-registry/templates/core.php.j2

Extend COmanage role so as to handle cache options

COmanage_role_core_cache_options

---

roles/comanage-registry/tasks/install.yml

COmanage tmp directory permissions

COmanage_tmp_directory_permissions

---

google2samlservers.yml
orcid2samlservers.yml

This PR adds playbooks for
- ORCID login proxy
- Google login proxy

Add playbooks for social login proxy

---

roles/comanage-registry/defaults/main.yml
roles/comanage-registry/templates/core.php.j2

Add App.base configuration parameter to core.php file

Add_app_base_config_core.php

---

README.md
d4science2samlservers.yml
deep2samlservers.yml
google2samlservers.yml
oauth2samlservers.yml
roles/ssp-modules/tasks/configure-common.yml
roles/ssp-modules/templates/module_rciaminfo-release-2.0.php.j2
roles/ssp-modules/templates/module_themevanilla-release-3.0.php.j2
roles/ssp/defaults/main.yml
roles/ssp/tasks/configure-common.yml
roles/ssp/templates/config/config-metarefresh-1.18.php.j2
roles/ssp/templates/metadata/saml20-idp-hosted-1.18.php.j2
saml2samlservers.yml
webservers.yml

This PR introduces the following changes:
- Add logrotate role in saml2samlservers playbook
- Add new playbooks for each SSP instance
- Add roles and tags in existing playbooks
- Style changes in templates
- Add `sources_raw` variable to metarefresh template

Add new playbooks and minor template improvements

---

roles/comanage-registry-plugins/tasks/configure.yml
roles/comanage-registry/defaults/main.yml
roles/comanage-registry/tasks/configure.yml

Add task to configure cron jobs for comanage-registry

Add_cron_task_comanage_registry

---

roles/keycloak/defaults/main.yml
roles/keycloak/tasks/install_plugin.yml
roles/keycloak/tasks/main.yml
roles/keycloak/templates/keycloak.service.j2

Install keycloak as a different user "{{keycloak_service_user}}" than the ssh connected one
Service runs with user '"{{keycloak_service_user}}"
where **keycloak_service_user** is a configured variable

Install keycloak as a different user

---

roles/keycloak/tasks/main.yml

More information [here](https://jira.argo.grnet.gr/browse/RCIAM-715)

Comparing archives by SHA1 before replacing files

---

roles/ssp-modules/tasks/install-common.yml

Add tag:ssp-modules:install:repo for ssp-modules install common

ssp_modules_tag_repo

---

roles/ssp-modules/tasks/install-common.yml

Improve ssp-module zip deployment

Improvemenet_ssp-modules_zip_handle

---

roles/rciam-utils/templates/rciam-ip2country/config.py.j2
roles/rciam-utils/templates/rciam-sync-client-names/config.py.j2
templates/rciam-ip2country/config.py.j2
templates/rciam-sync-client-names/config.py.j2

Change db host values for rciam-ip2country and rciam-sync-client-names

---

roles/rciam-probes/tasks/install-RedHat.yml

Upgrade pip3 and install pip3 dependencies

Monitor_role_deploy_pip3_dependencies

---

roles/ssp-modules/defaults/main.yml
roles/ssp-modules/templates/module_themevanilla-release-3.0.php.j2

Configuration for Noty Top bar

Noty_top_bar_configuration

---

roles/keycloak/defaults/main.yml
roles/keycloak/tasks/blocks/configure_idp_mappers.yml
roles/keycloak/tasks/blocks/helpers/get_idp_mappers_list.yml
roles/keycloak/tasks/configure.yml

this is for https://jira.argo.grnet.gr/browse/RCIAM-700

Keycloak role now supports adding/updating IdP mappers

---

roles/keycloak/tasks/main.yml
roles/keycloak/templates/15.0.2/standalone-ha.xml.j2

see description [here](https://jira.argo.grnet.gr/browse/RCIAM-709)

Apply RCIAM-709 keycloak main logging config, plus a minor bugfix

---

roles/comanage-registry-plugins/tasks/configure.yml
roles/comanage-registry-plugins/tasks/main.yml
roles/comanage-registry/tasks/configure.yml

Add support for cron job env vars

Registry_cron_jobs_env_vars

---

roles/keycloak/tasks/configure.yml

Keycloak role

---

roles/keycloak/defaults/main.yml
roles/keycloak/tasks/blocks/configure_client_scope_mappers.yml
roles/keycloak/tasks/blocks/configure_client_scopes.yml
roles/keycloak/tasks/blocks/helpers/get_client_scopes_list.yml
roles/keycloak/tasks/configure.yml

Add client-scope configuration
In accordance to the ticket [RCIAM-793](https://jira.argo.grnet.gr/browse/RCIAM-793) 
Tested

Keycloak role changes for RCIAM-793

---

roles/keycloak/defaults/main.yml
roles/keycloak/tasks/blocks/configure_federation_mapper.yml
roles/keycloak/tasks/blocks/configure_federations.yml
roles/keycloak/tasks/blocks/configure_idp_mappers.yml
roles/keycloak/tasks/blocks/configure_saml_idps.yml
roles/keycloak/tasks/blocks/configure_social_idps.yml
roles/keycloak/tasks/blocks/helpers/get_realm_idps_list.yml
roles/keycloak/tasks/blocks/helpers/get_realm_keys.yml
roles/keycloak/tasks/blocks/helpers/search_realm_federations.yml
roles/keycloak/tasks/configure.yml
roles/keycloak/tasks/install_plugin.yml
roles/keycloak/tasks/main.yml
roles/keycloak/templates/keycloak.service.j2

This PR includes the following modifications:
- Rename the `config` variable into `keycloak_config`
- Changes the tags to have a `keycloak:` prefix
- Beautify the template placeholders, adds a space between curly brackets and variable
- Fixed a bug in the `get_realm_keys.yml` file
- Renamed tags `keycloak:configure:*` to `keycloak:config:*` ,  `keycloak:install_plugins` to `keycloak:install:plugins` and `keycloak:install_standaloneha` to `keycloak:install:standaloneha`

Mostly aesthetic mods and a small bugfix

---

roles/keycloak/defaults/main.yml
roles/keycloak/tasks/blocks/configure_default_idp.yml
roles/keycloak/tasks/configure.yml

This PR adds the functionality described [here](https://jira.argo.grnet.gr/browse/RCIAM-835)

[keycloak role] add default IdP redirector

---

README.md
roles/keycloak/tasks/configure.yml

**This PR should be merged ONLY after the `community.general` reaches the 4.5.0 release.** 
Check it [HERE](https://github.com/ansible-collections/community.general/releases)

Keycloak role - Added connection timeout on community.general.* tasks

---

README.md
roles/keycloak/tasks/configure.yml

Reverts rciam/rciam-deploy#115 until community.general v4.5.0 is released

Revert "Keycloak role - Added connection timeout on community.general.* tasks"

---

roles/keycloak/defaults/main.yml
roles/keycloak/handlers/main.yml
roles/keycloak/tasks/blocks/helpers/setup_logs_folder.yml
roles/keycloak/tasks/main.yml
roles/keycloak/templates/15.0.2/standalone-ha.xml.j2
roles/keycloak/templates/16.1.0/standalone-ha.xml.j2
roles/keycloak/templates/keycloak.service.j2
roles/keycloak/templates/logcleaner.sh.j2

This PR fulfills the objectives of  the following tickets:
- [RCIAM-852](https://jira.argo.grnet.gr/browse/RCIAM-852)
- [RCIAM-851](https://jira.argo.grnet.gr/browse/RCIAM-851)
- [RCIAM-883](https://jira.argo.grnet.gr/browse/RCIAM-883)

RCIAM 852 , RCIAM 851 and RCIAM-883

---

roles/keycloak/defaults/main.yml
roles/keycloak/tasks/blocks/client_registration_policies/create_update_client_reg_policy.yml
roles/keycloak/tasks/blocks/client_registration_policies/delete_client_reg_policy.yml
roles/keycloak/tasks/blocks/configure_client_reg_policies.yml
roles/keycloak/tasks/configure.yml

As requested in [this ticket](https://jira.argo.grnet.gr/browse/RCIAM-896)

[keycloak role] Allow creating updating and deleting client registration policies

---

roles/keycloak/tasks/blocks/client_registration_policies/create_update_client_reg_policy.yml
roles/keycloak/tasks/blocks/client_registration_policies/delete_client_reg_policy.yml
roles/keycloak/tasks/blocks/configure_client_reg_policies.yml
roles/keycloak/tasks/blocks/roles_configuration/clients/add_remove_client_default_roles.yml
roles/keycloak/tasks/blocks/roles_configuration/configure_default_roles.yml
roles/keycloak/templates/keycloak.service.j2

[keycloak role] Some bugfixes

---

roles/keycloak/defaults/main.yml
roles/keycloak/tasks/blocks/configure_event_logging.yml
roles/keycloak/tasks/configure.yml

See [this ticket](https://jira.argo.grnet.gr/browse/RCIAM-886)

[keycloak role] Adds the ability to configure realm's login and admin events

---

README.md
roles/keycloak/tasks/configure.yml

Keycloak role - Altered the way the wayf selection on realm config is done

---

federation-registry.yml
roles/federation-registry/defaults/main.yml
roles/federation-registry/files/ecosystem.config.js
roles/federation-registry/tasks/configure-ams.yml
roles/federation-registry/tasks/configure-environment.yml
roles/federation-registry/tasks/deploy.yml
roles/federation-registry/tasks/main.yml
roles/federation-registry/tasks/postgres.yml
roles/federation-registry/templates/ams-env.j2
roles/federation-registry/templates/ams_authorized_users.j2
roles/federation-registry/templates/ams_push_body.j2
roles/federation-registry/templates/db_config.j2
roles/federation-registry/templates/express-env.j2
roles/federation-registry/templates/pm2_config.j2
roles/federation-registry/templates/react-config.j2

Added federation-demo role that deploys the latest version of the federation-registry project. In more details the role performs the following actions:
1) It prepares the target host by installing all required packages and tools
2) It clones the project from github
3) It installs and configures the node projects (federation-registry-frontend,federation-registry-backend-api,federation-registry-backend-ams-agent)
4) It creates and configures the postgresql database if necessary
5) It creates and configures the ams topics and subscriptions if necessary

Federation registry role

---

roles/keycloak/templates/15.0.2/standalone-ha.xml.j2
roles/keycloak/templates/16.1.0/standalone-ha.xml.j2

added a validation entry in keycloak's DB connection config, to allow reconnection after database restarts

RCIAM-1000: [keycloak role]

---

roles/keycloak/tasks/blocks/configure_theme.yml

This aligns the role to the recent change of theme's paths.
The theme paths were changed to adapt to the upcoming quarkus-based keycloak.

[keycloak role] : aligned with a theme config change

---

roles/keycloak/templates/18.0.0/quarkus.properties.j2

More information here
https://jira.argo.grnet.gr/browse/RCIAM-1055

Rciam-1055

---

registryservers-roles-ui.yml
registryservers.yml
roles/cm-role-ui/defaults/main.yml
roles/cm-role-ui/tasks/configure-common.yml
roles/cm-role-ui/tasks/install-common.yml
roles/cm-role-ui/tasks/main.yml
roles/cm-role-ui/templates/configuration.php.j2

CM_roles_simple_ui

---

roles/comanage-registry/tasks/static_files.yml

Delegate copy of files to localhost

COmange_delegate_copy

---

cmrolesuiservers.yml

Add cm roles ui server playbook

Roles_simple_ui

---

roles/ssp-modules/tasks/install-common.yml

Download and deploy zip release

Theme_unzip

---

roles/comanage-registry/defaults/main.yml
roles/comanage-registry/tasks/configure.yml
roles/comanage-registry/templates/bootstrap.php.j2

Add support for COmanage bootstrap.php configuration

COmanage_bootstrap_config

---

roles/federation-registry/tasks/configure-ams.yml
roles/federation-registry/tasks/configure-environment.yml
roles/federation-registry/tasks/deploy.yml
roles/federation-registry/templates/ams_push_body.j2
roles/federation-registry/templates/express-env.j2
roles/federation-registry/templates/react-config.j2

- Updated Authentication with AMS
- Setup Base Url for Frontend
- Updated Paths for Deployment

Fedearation Registry Role Update

---

roles/federation-registry/defaults/main.yml
roles/federation-registry/tasks/configure-environment.yml
roles/federation-registry/tasks/deploy.yml

Removed Github Access Key Code (depricated)

 Federation Registry Update Role

---

roles/keycloak/tasks/blocks/configure_default_idp.yml

We must check : 
- IdP redirect is working
- authentication.updateProfileFirstLogin:"off" is changing the update profile to off.

review profile config Keycloak
